# Generated by Django 5.2.1 on 2025-05-28 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                ("house_number", models.CharField(max_length=10, verbose_name="House Number")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                ("model", models.CharField(blank=True, max_length=100, null=True, verbose_name="Model")),
                ("release_date", models.DateField(blank=True, null=True, verbose_name="Release Date")),
            ],
        ),
        migrations.CreateModel(
            name="SalesNetworkCell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Cell Name")),
                (
                    "hierarchy_level",
                    models.PositiveIntegerField(
                        choices=[(0, "Factory"), (1, "Retail Network"), (2, "Individual Entrepreneur")],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Hierarchy Level",
                    ),
                ),
                ("debt", models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Debt")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.contact",
                        verbose_name="Contact Information",
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="api.product", verbose_name="Products")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.salesnetworkcell",
                        verbose_name="Supplier",
                    ),
                ),
            ],
        ),
    ]
