# Generated by Django 5.2.1 on 2025-05-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["email"], "verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="salesnetworkcell",
            options={
                "ordering": ["hierarchy_level", "name"],
                "verbose_name": "Sales Network Cell",
                "verbose_name_plural": "Sales Network Cells",
            },
        ),
    ]
