# Generated by Django 5.2.1 on 2025-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contact_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesnetworkcell",
            name="hierarchy_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Display Name"),
        ),
    ]
