# Generated by Django 5.2.1 on 2025-05-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_salesnetworkcell_hierarchy_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesnetworkcell",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contact",
                verbose_name="Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="salesnetworkcell",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="api.product", verbose_name="Products"),
        ),
    ]
